apiVersion: apps/v1
kind: Deployment
metadata:
  name: isabella
spec:
  replicas: 2
  selector:
    matchLabels:
      app: isabella
  template:
    metadata:
      labels:
        app: isabella
    spec:
      containers:
      - name: isabella
        image: jdemo.azurecr.io/isabella
        env:
        - name: SOURCE_SVC
          value: faysarah
        - name: SINK_SVC
          value: tina
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            cpu: "2.5"
            nvidia.com/gpu: 1
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred2
---
apiVersion: v1
kind: Service
metadata:
  name: isabella
  namespace: default
  labels:
    app: isabella
spec:
  selector:
    app: isabella
  ports:
  - name: metrics
    port: 8000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: isabella
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: isabella
  endpoints:
  - port: metrics