apiVersion: apps/v1
kind: Deployment
metadata:
  name: tina
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tina
  template:
    metadata:
      labels:
        app: tina
    spec:
      containers:
      - name: tina
        image: jdemo.azurecr.io/tina
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred2
---
apiVersion: v1
kind: Service
metadata:
  name: tina
  namespace: default
spec:
  selector:
    app: tina
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8083
