apiVersion: apps/v1
kind: Deployment
metadata:
  name: tina
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tina
  template:
    metadata:
      labels:
        app: tina
    spec:
      containers:
      - name: tina
        image: jdemo.azurecr.io/tina
        imagePullPolicy: Always
        env:
        - name: THRESHOLD
          value: "1.7"
      imagePullSecrets:
      - name: regcred2
---
apiVersion: v1
kind: Service
metadata:
  name: tina
  namespace: default
  labels:
    app: tina
spec:
  selector:
    app: tina
  ports:
  - name: grpc
    port: 80
    targetPort: 8083
  - name: metrics
    port: 8000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tina
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: tina
  endpoints:
  - port: metrics
